export default {

  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  PHOTO_CREATED: 'PHOTO_CREATED',
  MYPHOTOS_RECEIVED:'MYPHOTOS_RECEIVED',
  MYPHOTO_DELETE:'MYPHOTO_DELETE',
  
  UPDATE_USER:'UPDATE_USER'

}