export default {

  UPDATE_USER: 'UPDATE_USER',
  LOGOUT: 'LOGOUT',
  CHANGE_PHOTOLISTTYPE: 'CHANGE_PHOTOLISTTYPE',
  TOGGLE_UPLOAD: 'TOGGLE_UPLOAD',
  ADD_MYPHOTOS: 'ADD_MYPHOTOS',
  ADD_UPLOAINGPHOTOS: 'ADD_UPLOAINGPHOTOS',
  UPLOADED_PHOTO: 'UPLOADED_PHOTO',
  RECEIVE_MYPHOTOS: 'RECEIVE_MYPHOTOS',
  RECEIVE_FRIENDPHOTOS: 'RECEIVE_FRIENDPHOTOS',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
  CLOSE_MESSAGE: 'CLOSE_MESSAGE',
  CLICK_PHOTO: 'CLICK_PHOTO',
  DESTORY_DISPLAY: 'DESTORY_DISPLAY',
  TOGGLE_COMMENT: 'TOGGLE_COMMENT',
  REMOVE_MYPHOTO: 'REMOVE_MYPHOTO'

}